Fix style nits

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -22,9 +22,7 @@ WGET=`which wget 2> /dev/null`
 BZIP2=`which bzip2 2> /dev/null`
 TAR=`which tar 2> /dev/null`
 GAWK=`which awk 2> /dev/null`
-if test "-$WGET-" = "--" || test "-$BZIP2-" = "--" || test "-$TAR-" = "--" \
-  || test "-$GAWK-" = "--"
-then
+if [[ -z $WGET || -z $BZIP2 || -z $TAR || -z $GAWK ]]; then
   echo You must install wget, tar, gawk and bzip2 to use apt-cyg.
   exit 1
 fi
@@ -71,14 +69,12 @@ function findworkspace()
 
   # work wherever setup worked last, if possible
 
-  if test -e /etc/setup/last-cache
-  then
+  if [[ -f /etc/setup/last-cache ]]; then
     tmp="`head -1 /etc/setup/last-cache`"
     cache="`cygpath -au "$tmp"`"
   fi
 
-  if test -e /etc/setup/last-mirror
-  then
+  if [[ -f /etc/setup/last-mirror ]]; then
     mirror="`head -1 /etc/setup/last-mirror`"
   fi
   mirrordir="`echo "$mirror" | sed -e "s/:/%3a/g" -e "s:/:%2f:g"`"
@@ -92,20 +88,17 @@ function findworkspace()
 
 function getsetup()
 {
-  if test "$noscripts" == "0" -a "$noupdate" == "0"
-  then
+  if [[ $noscripts -eq 0 && $noupdate -eq 0 ]]; then
     touch setup.ini
     mv setup.ini setup.ini-save
     wget -N $mirror/setup.bz2
-    if test -e setup.bz2 && test $? -eq 0
-    then
+    if [[ -f setup.bz2 && $? -eq 0 ]]; then
       bunzip2 setup.bz2
       mv setup setup.ini
       echo Updated setup.ini
     else
       wget -N $mirror/setup.ini
-      if test -e setup.ini && test $? -eq 0
-      then
+      if [[ -f setup.ini && $? -eq 0 ]]; then
         echo Updated setup.ini
       else
         mv setup.ini-save setup.ini
@@ -118,8 +111,7 @@ function getsetup()
 
 function checkpackages()
 {
-  if test "-$packages-" = "--"
-  then
+  if [[ -z $packages ]]; then
     echo Nothing to do, exiting
     exit 0
   fi
@@ -138,8 +130,7 @@ filepackages=""
 packages=""
 
 function process_args () {
-  while test $# -gt 0
-  do
+  while [[ $# -gt 0 ]]; do
     case "$1" in
 
       --mirror|-m)
@@ -173,8 +164,7 @@ function process_args () {
       ;;
 
       --file|-f)
-        if ! test "-$2-" = "--"
-        then
+        if [[ -n $2 ]]; then
           file="$2"
           dofile=1
           shift
@@ -195,8 +185,7 @@ function process_args () {
      ;;
 
       update|show|search|find|describe|packageof|install|remove)
-        if test "-$command-" = "--"
-        then
+        if [[ -z $command ]]; then
           command=$1
         else
           packages="$packages $1"
@@ -216,10 +205,10 @@ function process_args () {
 }
 
 # Check to see if global options are defined
-if [[ ! -z "$APTCYG_OPTIONS" ]] ; then
+if [[ -n $APTCYG_OPTIONS ]]; then
   # If we only have one element, assume it's a string to split
   #  and parse as an array
-  if [[ "${#APTCYG_OPTIONS[*]}" -eq "1" ]] ; then
+  if [[ ${#APTCYG_OPTIONS[*]} -eq 1 ]]; then
     APTCYG_OPTIONS=($APTCYG_OPTIONS)
   fi
   process_args "${APTCYG_OPTIONS[@]}"
@@ -227,10 +216,8 @@ fi
 
 process_args "$@"
 
-if test $dofile = 1
-then
-  if test -f "$file"
-  then
+if [[ $dofile -eq 1 ]]; then
+  if [[ -f $file ]]; then
     filepackages="$filepackages `cat "$file" | awk '{printf "%s ", $0}'`"
   else
     echo File $file not found, skipping
@@ -263,14 +250,13 @@ case "$command" in
     findworkspace
     getsetup
 
-    for pkg in $packages
-    do
+    for pkg in $packages; do
       echo ""
       echo Searching for installed packages matching $pkg:
       awk -v nocase="$nocase" '/[^ ]+ [^ ]+ 0/ { if (nocase == 1 ) { IGNORECASE=1 } if ($1 ~ query) { print $1 } }' query="$pkg" /etc/setup/installed.db
       echo ""
       echo Searching for installable packages matching $pkg:
-      if [[ "$nocase" -eq "1" ]] ; then
+      if [[ $nocase -eq 1 ]]; then
         cat setup.ini | awk -v query="$pkg" \
           'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {IGNORECASE=1; if ($1 ~ query) {print $1}}'
       else
@@ -287,8 +273,7 @@ case "$command" in
     checkpackages
     findworkspace
     getsetup
-    for pkg in $packages
-    do
+    for pkg in $packages; do
       echo ""
       cat setup.ini | awk -v nocase="$nocase" -v query="$pkg" \
         'BEGIN{RS="\n\n@ "; FS="\n"; ORS="\n"} {if (nocase == 1 ) { IGNORECASE=1 } if ($1 ~ query) {print $0 "\n"}}'
@@ -300,18 +285,14 @@ case "$command" in
   packageof)
 
     checkpackages
-    for pkg in $packages
-    do
+    for pkg in $packages; do
       key=`which "$pkg" 2>/dev/null | sed "s:^/::"`
-      if test "-$key-" = "--"
-      then
+      if [[ -z $key ]]; then
         key="$pkg"
       fi
-      for manifest in /etc/setup/*.lst.gz
-      do
+      for manifest in /etc/setup/*.lst.gz; do
         found=`cat $manifest | gzip -d | grep -c "$key"`
-        if test $found -gt 0
-        then
+        if [[ $found -gt 0 ]]; then
           package=`echo $manifest | sed -e "s:/etc/setup/::" -e "s/.lst.gz//"`
           echo Found $key in the package $package
         fi
@@ -337,9 +318,9 @@ case "$command" in
       pkg_lookup[$pkg]="$pkg"
 
       # case insensitive search
-      if [[ "$nocase" -eq "1" ]] ; then
+      if [[ $nocase -eq 1 ]]; then
         already=`grep -ic "^$pkg " /etc/setup/installed.db`
-        if test $already -ge 1 ; then
+        if [[ $already -ge 1 ]]; then
           # get the proper name for the package
           proper_name=`grep -i "^$pkg " /etc/setup/installed.db | awk '{ print $1 }'`
           # set our lookup value
@@ -352,17 +333,17 @@ case "$command" in
         already=`grep -c "^$pkg " /etc/setup/installed.db`
       fi
 
-      if test $already -ge 1 ; then
+      if [[ $already -ge 1 ]]; then
         pkg_already_installed[$pkg]="1"
         continue
       fi
 
       # check for new packages and find their proper names
-      if [[ "$nocase" -eq "1" ]] ; then
+      if [[ $nocase -eq 1 ]]; then
         proper_name=`cat setup.ini | awk -v package="$pkg" \
           'BEGIN{IGNORECASE=1; RS="\n\n@ "; FS="\n"} { if ($1 == package) { propername = $1 ; desc = $0; px++ } } \
            END {if (px == 1 && desc != "") { print propername ; exit 0 } else { print "Package not found" ; exit 1 } }'`
-        if [[ "$?" != "0" ]] ; then
+        if [[ $? -ne 0 ]]; then
           echo "Could not find $pkg, aborting..."
           exit
         else
@@ -373,122 +354,112 @@ case "$command" in
       fi
     done
 
-    for pkg in $packages
-    do
-    if [[ ${pkg_already_installed[$pkg]} -eq 1 ]] ; then
-      echo "Package $pkg is already installed, skipping"
-      continue
-    fi
-
-    echo Installing $pkg as ${pkg_lookup[$pkg]}...
-    user_pkg_name="$pkg"
-    pkg="${pkg_lookup[$pkg]}"
-
-    echo ""
-    echo Installing $pkg
-
-    # look for package and save desc file
-
-    mkdir -p "release/$pkg"
-    cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
-      'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
-       END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
-
-    desc=`cat "release/$pkg/desc"`
-    if test "-$desc-" = "-Package not found-"
-    then
-      echo Package $pkg not found or ambiguous name, exiting
-      rm -r "release/$pkg"
-      exit 1
-    fi
-    echo Found package $pkg
-
-    # download and unpack the bz2 file
-
-    # pick the latest version, which comes first
-    install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
-    category=`cat "release/$pkg/desc" | awk '/^category: / { print $2; exit }'`
-    requires=`cat "release/$pkg/desc" | awk '/^requires: / { print $2; exit }'`
-
-    if test "-$install-" = "--"
-    then
-      if [[ "$category" == "_obsolete" && ! -z "$requires" ]] ; then
-        echo "$pkg is obsolete and replaced by: $requires"
-      else
-        echo "Could not find \"install\" in package description: obsolete package?"
+    for pkg in $packages; do
+      if [[ ${pkg_already_installed[$pkg]} -eq 1 ]]; then
+        echo "Package $pkg is already installed, skipping"
+        continue
       fi
-      exit 1
-    fi
 
-    file=`basename $install`
-    cd "release/$pkg"
-    wget -nc $mirror/$install
+      echo Installing $pkg as ${pkg_lookup[$pkg]}...
+      user_pkg_name="$pkg"
+      pkg="${pkg_lookup[$pkg]}"
 
-    # check the md5
-    digest=`cat "desc" | awk '/^install: / { print $4; exit }'`
-    digactual=`md5sum $file | awk '{print $1}'`
-    if ! test $digest = $digactual
-    then
-      echo MD5 sum did not match, exiting
-      exit 1
-    fi
+      echo ""
+      echo Installing $pkg
 
-    echo "Unpacking..."
-    cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
-    gzip -f "/etc/setup/$pkg.lst"
-    cd ../..
+      # look for package and save desc file
 
+      mkdir -p "release/$pkg"
+      cat setup.ini | awk > "release/$pkg/desc" -v package="$pkg" \
+        'BEGIN{RS="\n\n@ "; FS="\n"} {if ($1 == package) {desc = $0; px++}} \
+         END {if (px == 1 && desc != "") print desc; else print "Package not found"}'
 
-    # update the package database
+      desc=`cat "release/$pkg/desc"`
+      if [[ $desc == "Package not found" ]]; then
+        echo Package $pkg not found or ambiguous name, exiting
+        rm -r "release/$pkg"
+        exit 1
+      fi
+      echo Found package $pkg
 
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
-      '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
-       END{if (ins != 1) print pkg " " bz " 0"}'
-    mv /etc/setup/installed.db /etc/setup/installed.db-save
-    mv /tmp/awk.$$ /etc/setup/installed.db
+      # download and unpack the bz2 file
 
+      # pick the latest version, which comes first
+      install=`cat "release/$pkg/desc" | awk '/^install: / { print $2; exit }'`
+      category=`cat "release/$pkg/desc" | awk '/^category: / { print $2; exit }'`
+      requires=`cat "release/$pkg/desc" | awk '/^requires: / { print $2; exit }'`
 
-    # recursively install required packages
-
-    echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
-    requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
-
-    warn=0
-    if ! test "-$requires-" = "--"
-    then
-      echo Package $pkg requires the following packages, installing:
-      echo $requires
-      for package in $requires
-      do
-        already=`grep -c "^$package " /etc/setup/installed.db`
-        if test $already -ge 1
-        then
-          echo Package $package is already installed, skipping
-          continue
+      if [[ -z $install ]]; then
+        if [[ $category == "_obsolete" && -n $requires ]]; then
+          echo "$pkg is obsolete and replaced by: $requires"
+        else
+          echo "Could not find \"install\" in package description: obsolete package?"
         fi
-        apt-cyg --noscripts install $package
-        if ! test $? = 0 ; then warn=1; fi
-      done
-    fi
-    if ! test $warn = 0
-    then
-      echo "Warning: some required packages did not install, continuing"
-    fi
+        exit 1
+      fi
 
-    # run all postinstall scripts
+      file=`basename $install`
+      cd "release/$pkg"
+      wget -nc "$mirror/$install"
 
-    pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
-    if test $pis -gt 0 && ! test $noscripts -eq 1
-    then
-      echo Running postinstall scripts
-      for script in /etc/postinstall/*.sh
-      do
-        $script
-        mv $script $script.done
-      done
-    fi
+      # check the md5
+      digest=`cat "desc" | awk '/^install: / { print $4; exit }'`
+      digactual=`md5sum $file | awk '{print $1}'`
+      if [[ $digest != $digactual ]]; then
+        echo MD5 sum did not match, exiting
+        exit 1
+      fi
 
-    echo Package $pkg installed
+      echo "Unpacking..."
+      cat $file | bunzip2 | tar > "/etc/setup/$pkg.lst" xvf - -C /
+      gzip -f "/etc/setup/$pkg.lst"
+      cd ../..
+
+
+      # update the package database
+
+      cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" -v bz=$file \
+        '{if (ins != 1 && pkg < $1) {print pkg " " bz " 0"; ins=1}; print $0} \
+         END{if (ins != 1) print pkg " " bz " 0"}'
+      mv /etc/setup/installed.db /etc/setup/installed.db-save
+      mv /tmp/awk.$$ /etc/setup/installed.db
+
+
+      # recursively install required packages
+
+      echo > /tmp/awk.$$ '/^requires: / {s=gensub("(requires: )?([^ ]+) ?", "\\2 ", "g", $0); print s}'
+      requires=`cat "release/$pkg/desc" | awk -f /tmp/awk.$$`
+
+      warn=0
+      if [[ -n $requires ]]; then
+        echo Package $pkg requires the following packages, installing:
+        echo $requires
+        for package in $requires; do
+          already=`grep -c "^$package " /etc/setup/installed.db`
+          if [[ $already -ge 1 ]]; then
+            echo Package $package is already installed, skipping
+            continue
+          fi
+          apt-cyg --noscripts install $package
+          if [[ $? -ne 0 ]]; then warn=1; fi
+        done
+      fi
+      if [[ $warn -ne 0 ]]; then
+        echo "Warning: some required packages did not install, continuing"
+      fi
+
+      # run all postinstall scripts
+
+      pis=`ls /etc/postinstall/*.sh 2>/dev/null | wc -l`
+      if [[ $pis -gt 0 && $noscripts -ne 1 ]]; then
+        echo Running postinstall scripts
+        for script in /etc/postinstall/*.sh; do
+          $script
+          mv $script $script.done
+        done
+      fi
+
+      echo Package $pkg installed
 
     done
 
@@ -498,49 +469,41 @@ case "$command" in
   remove)
 
     checkpackages
-    for pkg in $packages
-    do
+    for pkg in $packages; do
+      already=`grep -c "^$pkg " /etc/setup/installed.db`
+      if [[ $already -eq 0 ]]; then
+        echo Package $pkg is not installed, skipping
+        continue
+      fi
 
-    already=`grep -c "^$pkg " /etc/setup/installed.db`
-    if test $already = 0
-    then
-      echo Package $pkg is not installed, skipping
-      continue
-    fi
+      dontremove="cygwin coreutils gawk bzip2 tar wget bash"
+      for req in $dontremove; do
+        if [[ $pkg == $req ]]; then
+          echo apt-cyg cannot remove package $pkg, exiting
+          exit 1
+        fi
+      done
 
-    dontremove="cygwin coreutils gawk bzip2 tar wget bash"
-    for req in $dontremove
-    do
-      if test "-$pkg-" = "-$req-"
-      then
-        echo apt-cyg cannot remove package $pkg, exiting
+      if [[ ! -f "/etc/setup/$pkg.lst.gz" ]]; then
+        echo Package manifest missing, cannot remove $pkg.  Exiting
         exit 1
       fi
-    done
+      echo Removing $pkg
 
-    if ! test -e "/etc/setup/$pkg.lst.gz"
-    then
-      echo Package manifest missing, cannot remove $pkg.  Exiting
-      exit 1
-    fi
-    echo Removing $pkg
+      # run preremove scripts
 
-    # run preremove scripts
+      if [[ -f "/etc/preremove/$pkg.sh" ]]; then
+        "/etc/preremove/$pkg.sh"
+        rm "/etc/preremove/$pkg.sh"
+      fi
 
-    if test -e "/etc/preremove/$pkg.sh"
-    then
-      "/etc/preremove/$pkg.sh"
-      rm "/etc/preremove/$pkg.sh"
-    fi
-
-    cat "/etc/setup/$pkg.lst.gz" | gzip -d | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
-    rm "/etc/setup/$pkg.lst.gz"
-    rm -f /etc/postinstall/$pkg.sh.done
-    cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}'
-    mv /etc/setup/installed.db /etc/setup/installed.db-save
-    mv /tmp/awk.$$ /etc/setup/installed.db
-    echo Package $pkg removed
-
+      cat "/etc/setup/$pkg.lst.gz" | gzip -d | awk '/[^\/]$/ {print "rm -f \"/" $0 "\""}' | sh
+      rm "/etc/setup/$pkg.lst.gz"
+      rm -f /etc/postinstall/$pkg.sh.done
+      cat /etc/setup/installed.db | awk > /tmp/awk.$$ -v pkg="$pkg" '{if (pkg != $1) print $0}'
+      mv /etc/setup/installed.db /etc/setup/installed.db-save
+      mv /tmp/awk.$$ /etc/setup/installed.db
+      echo Package $pkg removed
     done
 
   ;;
@@ -552,4 +515,3 @@ case "$command" in
   ;;
 
 esac
-
